### ISSUE TITLE
Make the original JSON available to edit in the text editor

### ISSUE THREAD

**Issue by nnseva** [nnseva/django-jsoneditor#14]
Make some kind of dual-editing tool of the JSON field, one as existent, and other as original JSON text (probable colorized).
##

**Comment by nnseva** [comment]
fixed in d2c881626bc447a426dc5572ec842054e8200ac9

v.0.0.9

**Comment by nnseva** [comment]
The new version of the Javascript library (5.7.0) causes wrong clipping of the context menu, while the old one (4.2.1) does not support selecting editor properly. Need to fix it

**Comment by demux** [comment]
How do we enable this dual editing mode?

**Comment by nnseva** [comment]
> How do we enable this dual editing mode?

Really the new 5.7.0 version of the jsoneditor library allows to use dual editing mode and contains appropriate options, but unfortunately, causes wrong clipping of the context menu in django environment.

The old one 4.2.1 doesn't clip context menu, but doesn't support dual editing mode enough to use it in our case.

I've created the issue https://github.com/josdejong/jsoneditor/issues/416 but the author looks like not ready to fix it.

I am not ready to fix the jsoneditor package as well. Hope somebody will try to fix it. After the fix, I might enable an option to allow dual editing mode.

**Comment by flapedriza** [comment]
I have tried the tree + code mode with the latest jsoneditor version and now it seems to work correctly, the changes are in #33

**Comment by nnseva** [comment]
Hi @flapedriza 

Neither 5.13.3 (last) nor 5.13.2 (used in your code) version of the jsoneditor allow overlapping external div (around a text input) by the context menu in the tree mode, so the context menu is clipped when the jsoneditor is used especially by the inline form. See here and try to call context menu https://jsfiddle.net/5m1dusu8/17/. The issue  josdejong/jsoneditor#416 remains open.

Both tested by me versions, 1.10 and 1.11, of the Django package, use some div around a form, which clips a tree context menu when it is called. What the Django version do you use?

**Comment by nnseva** [comment]
the #43 fixes it finally and also some customization features has been added
