### ISSUE TITLE
Integrate JSONEditor with new postgreSQL-specific django JSONField [$10 awarded]

### ISSUE THREAD

**Issue by nnseva** [nnseva/django-jsoneditor#16]
django starting 1.9: https://docs.djangoproject.com/ja/1.9/ref/contrib/postgres/fields/
##

**Comment by evdoks** [comment]
+1

**Comment by nnseva** [comment]
Done

126d18d
170ea89
9dfdfea

**Comment by sadan** [comment]
@nnseva I am using Postgres JSON field in my model, I've replaced that with the your JSONField as mentioned in the _Readme_ but in admin it's showing the json as a string in the editor. I've also configured the Model admin as well.

<img width="1382" alt="screen shot 2019-02-25 at 3 46 10 pm" src="https://user-images.githubusercontent.com/15120052/53332182-7f564480-3914-11e9-9b99-84e73cac1f64.png">

I am using the latest version of the package from Git.

**Comment by nnseva** [comment]
Will look into ...

**Comment by nnseva** [comment]
Hi @sadan,

> @nnseva I am using Postgres JSON field in my model, I've replaced that with the your JSONField as mentioned in the _Readme_ but in admin it's showing the json as a string in the editor. I've also configured the Model admin as well.
> 
> <img alt="screen shot 2019-02-25 at 3 46 10 pm" width="1382" src="https://user-images.githubusercontent.com/15120052/53332182-7f564480-3914-11e9-9b99-84e73cac1f64.png">
> 
> I am using the latest version of the package from Git.

I've reproduced you problem, it looks like some kind of conversion problem, probably because of migration or using some tool unknown to me.

It may also happen if your old code stores JSON into the database as a string, ignoring the fact that the field is not Text, but JSON, i.e. should take dictionary directly.

I propose you to look into your database. You will see the content of the table like the following:
```
... | features
----+------------------------------------------------------------------
... | "{\"logo_resolution\": {...
```
(NOTE: see the first doublequote!)

It means that the JSON content has been written to the database as *string containing representation of the string containing* JSON.

Such a way, when the Django reads database content as a string, the string contains *string value representation*, not the JSON itself. Let's try to start shell of your application, you probably will see something like the following:

```
$ python manage.py shell
...
>>> from mymodule.models import ... as M
>>> M.objects.all()[0].features
'{"logo_resolution": {...'
```
You see that the `features` field contains a string, while it should directly contain dictionary (represented as a string on the - lower - database layer only).

What you should do is - to convert string values back to the dictionary, doing it like the following:
```
$ python manage.py shell
...
>>> import json
>>> from mymodule.models import ... as M
>>> for o in M.objects.all():
...  if isinstance(o.features, str) and o.features:
...    o.features = json.loads(o.features)
...    o.save()
```

I hope it will help you
