### ISSUE TITLE
[Q] How to access the JSONEditor JS object?

### ISSUE THREAD

**Issue by peterlitvak** [nnseva/django-jsoneditor#20]
What would be the easiest way to access JSONEditor JS object in the rendered page?
I need to set JSON dynamically to the control (I assume it supports the set(JSON) method).
It would be easy to get the DOM object for the field ID but I'm not sure how to get to the JSONEditor JS object.

**Comment by nnseva** [comment]
Hi @peterlitvak ,

There are several editor instances may be present on the page, one per every JSON field. Unfortunately, I don't know any way to get access to these objects right now. You can see how they are constructed in `/jsoneditor/static/django-jsoneditor/django-jsoneditor.js` code, look for `var editor`.

Feel free to fix the code and README instructions as you wish and send me a pull request to extend a package capabilities.

**Comment by peterlitvak** [comment]
here we go
https://github.com/nnseva/django-jsoneditor/pull/21

**Comment by nnseva** [comment]
done

**Comment by wasabigeek** [comment]
@peterlitvak do you mean that we can change the config in `admin.py`? How would we do so (I prefer not to use the fixed implementations)?

**Comment by peterlitvak** [comment]
I think the change was merged in to main with pr #21

**Comment by wasabigeek** [comment]
@peterlitvak I guess you meant via the Javascript console then. Is it possible to change the modes of the editor instance via Javascript? I can't seem to access most of the methods.

**Comment by nnseva** [comment]
Hi @wasabigeek,

just check the `jsonEditors` object in the browser console to see, where you can find all installed editors.

Anyway, changing editor mode may cause problems with the [jsoneditor](https://github.com/josdejong/jsoneditor/) package used as a JS part of this package:

- the version 4 of the [jsoneditor](https://github.com/josdejong/jsoneditor/) package doesn't change mode properly
- the version 5 of the [jsoneditor](https://github.com/josdejong/jsoneditor/) package changes mode properly but cuts a context menu view as described here https://github.com/josdejong/jsoneditor/issues/416

I will watch the issue of the [jsoneditor](https://github.com/josdejong/jsoneditor/) package and change default [jsoneditor](https://github.com/josdejong/jsoneditor/) version from 4 to 5 as soon as it will be resolved. Then I will enable changing mode menu of the editor.
