### ISSUE TITLE
js 404 (Not Found)

### ISSUE THREAD

**Issue by psychok7** [nnseva/django-jsoneditor#22]
Hi, i was getting `http://localhost:8000/static/django-jsoneditor/django-jsoneditor.js 404 (Not Found)` and i got it working by copying the `js` here in the repository to my own static folder.

I am using Postgres built in JsonField mentioned here https://github.com/nnseva/django-jsoneditor/issues/16 and things seem to be working fine (after i fix the not found issue). I tested with `django-jsonfield` and everything works fine there.

I have my `forms.py`

```python
from jsoneditor.forms import JSONEditor

class Model1Form(forms.ModelForm):

    class Meta:
        model = Model1
        fields = '__all__'
        widgets = {
            'answer_data': JSONEditor()
        }
```

and then in `admin.py` i just plug the `form=Model1Form`. I find this approach to be `less dirty` like mentioned [here](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_overrides)

**Comment by nnseva** [comment]
Hi @psychok7 ,

The most probable source of the problem is that you have changed `DEBUG=False` in your `settings.py` and did not run the `python manage.py collectstatic` command.

Also, the problem may be caused by absent `jsoneditor` in the `INSTALLED_APPS` list in the `settings.py` file.

**Comment by psychok7** [comment]
@nnseva I have all of that. If I don't use the now native postgresql Json field  it works fine. I only have this issue with the native one

**Comment by SeverinAlexB** [comment]
Same here

**Comment by nnseva** [comment]
@psychok7 @Sebubu could you please apply here the complete test example to reproduce the case?

**Comment by nnseva** [comment]
Hi @all

Try to use a new version of the package. It contains ready-to-use replacement for the postgresql-specific JSONField, as well as an example of it's using.

No any problem appears with static files, so your issue has not been reproduced.
