### ISSUE TITLE
jsoneditor with postgres depends on jsonfield?

### ISSUE THREAD

**Issue by sandroden** [nnseva/django-jsoneditor#25]
Hi, while reading the docs:

> jsoneditor.fields.postgres_jsonfield.JSONField replaces django.contrib.postgres.fields.JSONField

I thought it would just depend on django >= 1.9 on postgresql, but it really depends on jsonfield:

```
from django.contrib.postgres.fields import JSONField as _JSONField
from jsonfield.fields import JSONFormField as _JSONFormField

```
I think you should spell it clearly in the docs. the author of jsonfield suggests to use official json field from django.postgres

> All versions of Django from 1.8 onwards are tested, however, if you are using Postgres, I highly recommend that you consider using the django.contrib.postgres module’s JSONField instead.

When using the fixed version that depends on jsonfield, I realized that db stores data in a text field that is not what I wanted... is is possible to use jsoneditor with postgresql json field?

TIA

sandro
*:-)

**Comment by nnseva** [comment]
Oops, sure, it is an unnecessary dependency. Fixed in the master branch.
