### ISSUE TITLE
Doesn't parse pre-set fields from querystring

### ISSUE THREAD

**Issue by tpict** [nnseva/django-jsoneditor#26]
When passing pre-set field values into an add panel through the querystring, the JSONEditor field isn't automatically populated

**Comment by nnseva** [comment]
I've just checked this feature.

1. I didn't find any reference to this feature in the Django original documentation (please provide me a link if I miss something), but it really works.
2. The feature also works for the third-party jsonfield package(s), whether the JSONEditor is used or not.
3. The feature does NOT work for Django-provided postgresql-specific JSONField, whether the JSONEditor is used, or not.

You probably have used a Django-provided postgresql-specific JSONField. It doesn't work with the (undocumented?) feature you want to use. Please address this bug to Django developers.

**Comment by tpict** [comment]
I'm using the Django-provided postgres JSON field and the querystring feature is working for me on Django 1.9.7.

**Comment by nnseva** [comment]
Here the result of using Django-provided JSON field such a way:

```python
from django.db import models

#from jsoneditor.fields.postgres_jsonfield import JSONField
from django.contrib.postgres.fields import JSONField
# Create your models here.

class TestModel(models.Model):
    test_django_jsonfield = JSONField(verbose_name="Test JSON",null=True,blank=True,help_text="Test JSON editor for the django postgres-specific JSONField")

class TestSubModel1(models.Model):
    par = models.ForeignKey(TestModel)
    test_inline_json_field = JSONField(verbose_name="Test JSON",null=True,blank=True,help_text="Test JSON editor for the django postgres-specific JSONField")

class TestSubModel2(models.Model):
    par = models.ForeignKey(TestModel)
    test_inline_json_field = JSONField(verbose_name="Test JSON",null=True,blank=True,help_text="Test JSON editor for the django postgres-specific JSONField")
```

Here the console:

```console
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2017 - 11:18:03
Django version 1.9.7, using settings 'django_jsoneditor.settings_testapp2'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[26/Jun/2017 11:18:11] "GET /admin/testapp2/testmodel/add/?test_django_jsonfield={%22a%22:11} HTTP/1.1" 200 10599
...
```

As you can see, I am trying to pass an initial value `{"a":11}` to the Django-provided postgres-specific JSON field. As a result, the field gets a value enclosed to quotas, instead of structured value (bad result). All other third-party tested jsonfield types in available environments get a pure structured value (good result).

Are you sure that you didn't override django-provided JSON field by your own replacement?

![image](https://user-images.githubusercontent.com/496812/27536893-d4f88590-5a79-11e7-8be9-615efdf61c98.png)

**Comment by tpict** [comment]
I'm using `django.contrib.postgres`.

Try
```
?test_django_jsonfield=%7b%27a%27%3a11%7D
```
instead (output of Python `urlencode`)

**Comment by nnseva** [comment]
1. Your string is not a JSON. The JSON key names MUST be enclosed by double-quotes: http://www.json.org/.
2. Anyway, whether the querystring is encoded or not, whether the key is enclosed in quotes or double-quotes, the result is the same: field is filled-in by a string enclosed in double-quotes, instead of pure structured value.

**Comment by tpict** [comment]
I've played around with it a little and found that the querystring is correctly parsed for `HStoreField` but not `JSONField`.

I'll open a ticket in the Django issue tracker about the issue with `JSONField`, but `JSONEditor` isn't loading pre-set data even when it's given valid JSON data.

**Comment by nnseva** [comment]
Here the result of using third-party JSON field such a way:

```python
from django.db import models

#from jsoneditor.fields.django_json_field import JSONField as JSONField1
from jsoneditor.fields.django_jsonfield import JSONField as JSONField2
# Create your models here.

class TestModel(models.Model):
#    test_django_json_field = JSONField1(verbose_name="Test JSON 1",null=True,blank=True,help_text="Test JSON editor for the django-json-field from https://github.com/derek-schaefer/django-json-field")
    test_django_jsonfield = JSONField2(verbose_name="Test JSON 2",null=True,blank=True,help_text="Test JSON editor for the django-jsonfield from https://github.com/bradjasper/django-jsonfield")

class TestSubModel1(models.Model):
    par = models.ForeignKey(TestModel)
    test_inline_json_field = JSONField2(verbose_name="Test JSON 2",null=True,blank=True,help_text="Test JSON editor for the django-jsonfield from https://github.com/bradjasper/django-jsonfield")

class TestSubModel2(models.Model):
    par = models.ForeignKey(TestModel)
    test_inline_json_field = JSONField2(verbose_name="Test JSON 2",null=True,blank=True,help_text="Test JSON editor for the django-jsonfield from https://github.com/bradjasper/django-jsonfield")
```

Here the console:

```console
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2017 - 18:00:26
Django version 1.9.7, using settings 'django_jsoneditor.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[26/Jun/2017 18:00:31] "GET /admin/testapp/testmodel/add/?test_django_jsonfield={%22a%22:11,%22b%22:12} HTTP/1.1" 200 12075
[26/Jun/2017 18:00:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3217
```

As you can see, the passed value has been parsed and correctly displayed by the JSONEditor.

![image](https://user-images.githubusercontent.com/496812/27553055-379732f4-5ab2-11e7-9fd0-2b8da7de0168.png)
