### ISSUE TITLE
False(Boolean) is not show properly on django admin

### ISSUE THREAD

**Issue by raun** [nnseva/django-jsoneditor#28]
I have a JsonField where I want to store just False. On detail widget, it is not shown properly. However, when I tried to read it from the database it returns the correct value i.e. False(Type Boolean).

Here is the screenshot on changelist page : 
<img width="1912" alt="screen shot 2017-08-28 at 11 34 36 am" src="https://user-images.githubusercontent.com/2016794/29761090-0d5eb138-8be5-11e7-90f2-365931e08411.png">

However, on list view, I am able to see false for this object : 
<img width="962" alt="screen shot 2017-08-28 at 11 34 57 am" src="https://user-images.githubusercontent.com/2016794/29761109-3577e55e-8be5-11e7-957e-6c0eecc35eda.png">

If you can replicate this then I can work on making the change and sending you a PR.

**Comment by nnseva** [comment]
Hi @raun ,

What the particular version of the Django do you use?
What the particular JSONField package, or Django PostgeSQL-specific JSONField, do you use (if you use)?
What the code to use JSONEditor package do you use?

I see that you probably use a deprecated JSONField implementation package, or don't use a JSONField implementation at all. The JSON which is shown on the screenshot is not a JSON, but Python representation of the JSON-like variable instead (see config9, config10). Also, note that the config1-config8 strings are also not valid JSON strings at all.

The JSONEditor assumes that the field contains a valid JSON string, converted to/from JSON-like Python structure based on `dict`-s and `list`-s while used internally in the program.

**Comment by raun** [comment]
Hello @nnseva,

Thanks for the quick reply. I am using Django 1.11.2. I have django-mysql JsonField implementation. I see your point.

I would change my implementation to use JSON strings.
Closing.
