### ISSUE TITLE
Initialization runs in a loop every 10 milliseconds

### ISSUE THREAD

**Issue by dvarrazzo** [nnseva/django-jsoneditor#29]
https://github.com/nnseva/django-jsoneditor/blob/df4351e17d499924b8ce2e54ec2c5fc7519263d3/jsoneditor/static/django-jsoneditor/django-jsoneditor.js#L6

I assume you wanted to use `setTimeout()` to run this thing once, delayed, not forever. This is not a sane practice at either, but better than a busy loop.

**Comment by nnseva** [comment]
Hi @dvarrazzo,

Really I would like to run initialization only once, but I didn't find any proper way to resolve when the initialization should be evaluated.

Actually, some Django admin interface extenders like Django-Suit resolve such a problem generating a special finalization event for the generated admin forms in a browser context. Unfortunately, neither the standard Django admin interface nor the standard Django form does it.

Such a way, I've used some techniques to minimize processor load while "infinite" initialization, but I can not avoid this trick at all.

If you find some compatible way to resolve a proper moment to initialize editors, I would be happy to see a pull request from you.

**Comment by dvarrazzo** [comment]
I'm working on a customized version of your plugin for my project. There are several problems with your current implementation so it's in a state of flux really.

This is my current state, feel free to steal something. It solves initialization and also works when the widget is used in a tabular inline. Other changes were needed to the css, and I want to allow editor configuration from python, so I'm keeping on working on it.

```javascript
(function($) {

    var editors_init = function () {
        if (typeof(jsoneditor) == "undefined")
            jsoneditor = {JSONEditor: JSONEditor};

        $(".for_jsoneditor").each(function (i, v) { init_editor($(v)); });
    };

    var init_editor = function ($f) {
        var id = $f.attr("id") + "_jsoneditor";
        var name = $f.attr("name") + "_jsoneditor";
        if ($f.parents('.empty-form').length) {
            return;
        }
        var $nxt = $f.parent().find('#' + id);
        if ($nxt.attr("name") == name) {
            return;
        }
        var value = {};
        try {
            value = JSON.parse($f[0].value);
        } catch (e) {
            // ignore
        }
        $nxt.detach();
        $nxt = $('<div cols="40" rows="10" id="' + id + '" name="' + name + '"></div>');
        $f.parent().append($nxt);
        var fnc = function (f, nxt, value) {
            var editor = new jsoneditor.JSONEditor(nxt, {
                onChange: function () {
                    f.value = JSON.stringify(editor.get());
                },
                modes: ['tree', 'code'],
                search: true,
            }, value);

            return editor;
        };
        fnc($f[0], $nxt[0], value);
    };

    $(window).on('load', editors_init);

    $(document).on('formset:added', function (e, $row, fs_name) {
        $row.find(".for_jsoneditor").each(
                function (i, v) { init_editor($(v)); });
    });

})(django.jQuery);
```

**Comment by nnseva** [comment]
Hi @dvarrazzo,

I will probably try to use your code in the package. Anyway, I would happy to see a pull request from you.

I've noticed that you are trying to switch the mode selector and search functions on. Note that these functions work properly only in the 5th version of the JSONEditor javascript package, while the 5th version of the JSONEditor injects an action menu for the tree-like editor inside an outer div of the editor div. Such a way, relatively small outer div (like in the Django admin) leads to cutting the action menu in case of using a 5th version of the JSONEditor.

See here, the action menu on the right tab is hidden under the div with the orange frame.
![image](https://user-images.githubusercontent.com/496812/32052675-b14a938e-ba61-11e7-9239-842f4761177c.png)

The 4th version of the package, as the opposite, creates an action menu in the page body, so the action menu there is not covered by any div on the page. But I didn't find a way to tell the 4th version of the package work with mode switcher properly.

I've [created the issue](https://github.com/josdejong/jsoneditor/issues/416) for the JSONEditor javascript package but it waits for the evaluator a while.

**Comment by dvarrazzo** [comment]
I've notice the issue you mention. I've fixed it hacking the editor code itself. If they introduce a callback that'd be fine for me.

FYI I did the following, which works ok in Django admin:

```diff
index 06e512c..6130fe0 100644
--- a/json_editor/static/json_editor/js/jsoneditor.js
+++ b/json_editor/static/json_editor/js/jsoneditor.js
@@ -11931,6 +11931,15 @@ return /******/ (function(modules) { // webpackBootstrap
            ContextMenu.visibleMenu.hide();
          }
          ContextMenu.visibleMenu = this;
+
+         // piro: hack to avoid truncating the menu to the container
+         // move the menu to a larger parent container.
+         // TODO: to become a callback if implemented:
+         // https://github.com/josdejong/jsoneditor/issues/416
+         var p = $(this.dom.root);
+         var off = p.offset();
+         p.appendTo(p.parents('fieldset'));
+         p.offset(off);
        };
 
        /**
```

**Comment by nnseva** [comment]
Oh, this hack is not good enough... but it may be a source of ideas for the JSONEditor package developers. I will look for patches from them.

**Comment by nnseva** [comment]
Looks like the most problems are solved anyway, closing.
