### ISSUE TITLE
Displaying the variable name

### ISSUE THREAD

**Issue by kerryz** [nnseva/django-jsoneditor#34]
Thanks for a great widget!  
I'm wondering how I can see the variable name when using this widget.

Example:

In models.py
```
from django.db import models
from django.contrib.postgres.fields import JSONField

class AModel(models.Model):
    a_field = JSONField()
    b_field = JSOnField()
```

In admin.py
```
from .models import AModel
from django.contrib import admin

class AModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
        JSONField: {'widget': JSONEditor}
    }

admin.site.register(AModel, AModelAdmin)
```

This will enable me to edit the fields `a_field` and `b_field` in Django admin pages, but since the variable names `a_field` and `b_field` aren't displayed in the admin pages, I don't know which widget is editing which variable.

**Comment by nnseva** [comment]
Please report me:

1. What is the Django version you use
2. Did you change a JSONEditor JS/CSS paths in your settings.py file using
JSON_EDITOR_JS and JSON_EDITOR_CSS settings
3. Upload a screenshot of your admin page

**Comment by kerryz** [comment]
`Django==1.11.10`

```
JSON_EDITOR_JS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.13.3/jsoneditor.js'
JSON_EDITOR_CSS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.13.3/jsoneditor.css'
```

models.py
```python
material_hydraulic = models.CharField(max_length=128, null=True, blank=True)
phases = models.SmallIntegerField(null=True, blank=True)
h_max = models.FloatField(null=False)
graphs = JSONField()
data_misc = JSONField()
```

<img width="1617" alt="screen shot 2018-02-26 at 11 14 41" src="https://user-images.githubusercontent.com/4254060/36665089-ee6d3556-1ae6-11e8-8350-2e67af6d3973.png">

**Comment by nnseva** [comment]
Hi @kerryz,

It really looks like an incompatibility with the Django version 1.11.

Would you like to fix the problem and create a pull request?

**Comment by nnseva** [comment]
Hi @kerryz ,

The fixed version of the django-jsoneditor has just been issued.

63459352c5ed531d19e1bd2cf540aa7cd55725d9
