### ISSUE TITLE
Does not work in admin once the admin widgets load

### ISSUE THREAD

**Issue by radzhome** [nnseva/django-jsoneditor#35]
Shows up until you add the admin widgets to a field in the admin site.

```
from django.contrib.admin import widgets
self.fields['some_date'].widget = widgets.AdminDateWidget()
```

This causes:
```
Uncaught TypeError: django.jQuery is not a function
    at django-jsoneditor.js:3
```

**Comment by nnseva** [comment]
Please provide
- django version used and
- the minimal complete source code or project to reproduce the bug

**Comment by demty** [comment]
Hello, I encountered this bug too. 
Django: 2.1
django-jsoneditor: 0.0.12
At gist a minimal example to reproduce.
Problem is that js imports of jsoneditor comes before jquery imports, so django.Jquery that referenced in jsoneditor js files is undefined.
https://gist.github.com/demty/b15614e5095d7c63b522a987afeb21cf

**Comment by nnseva** [comment]
Sorry @demty @radzhome but the package is not compatible with Django v2+ yet see here #39 

You can suggest a pull request or [back the issue](https://www.bountysource.com/issues/64072050-full-support-for-django-v2)

**Comment by nnseva** [comment]
Good news @demty @radzhome the pull request #40 has fixed the compatibility issue
