### ISSUE TITLE
Support Django 2.1

### ISSUE THREAD

**Issue by vCra** [nnseva/django-jsoneditor#36]
Hi

In Django 2.1, Support for Widget.render() methods without the renderer argument is removed. The current render method does not accept the renderer argument

**Comment by nnseva** [comment]
Oh, thank you for the issue. I would very appreciate if you propose a pull request, or some bounty may boost a fix.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=61021118)](https://www.bountysource.com/issues/61021118-support-django-2-1)
