### ISSUE TITLE
Is there a way to expand the JSON?

### ISSUE THREAD

**Issue by viperfx** [nnseva/django-jsoneditor#41]
Can we configure it to be able to expand all JSON fields by default?

**Comment by nnseva** [comment]
You can access the underlying JSONEditor JS objects in your JavaScript via dictionary named jsonEditors. Just create your own Javascript code to expand all fields after the page download finished in the appropriate event.

**Comment by viperfx** [comment]
Okay thanks. Is there an example of the the jsonEditors field being used?

**Comment by nnseva** [comment]
A hook to pass `jsoneditor.JSONEditor` constructor parameters has been added, see README file. It may help.
