### ISSUE TITLE
JSON not encoded correctly in template

### ISSUE THREAD

**Issue by doctormo** [nnseva/django-jsoneditor#45]
The template `templates/django_admin_json_editor/editor.html` does not encode the schema in text area correctly. This is because python data is NOT the same as json data. The biggest difference is booleans, which are `True` in python but `true` in json. Using just `|safe` in the template means that the encoding is wrong.

A filter like this GIST: https://gist.github.com/amacneil/5af7cd0e934f5465b695 fixes the issue

```
      schema: {{ schema|json|safe }}
```

Tested schema, json schema 07 meta-schema: http://json-schema.org/draft-07/schema

**Comment by nnseva** [comment]
Hi @doctormo, the project doesn't contain any templates. What the template do you mean?

**Comment by doctormo** [comment]
Hmm, you have me worried I reported this bug to the wrong project. Sorry for the noise!
