### ISSUE TITLE
ModuleNotFoundError: No module named 'json_field

### ISSUE THREAD

**Issue by charanjit-singh** [nnseva/django-jsoneditor#47]
![image](https://user-images.githubusercontent.com/23359602/58747964-d6c5fc80-848f-11e9-858d-20e8fdb6ca98.png)

**Comment by charanjit-singh** [comment]
```  File "/media/charanjit/WorkStation/BN-Habitat/BN-Habitat_Backend/bnhabitat_backend/mainApp/models.py", line 3, in <module>
    from jsoneditor.fields.django_json_field import JSONField
  File "/media/charanjit/WorkStation/BN-Habitat/BN-Habitat_Backend/venv/lib/python3.7/site-packages/jsoneditor/fields/django_json_field.py", line 1, in <module>
    from json_field import JSONField as _JSONField
ModuleNotFoundError: No module named 'json_field'
```

**Comment by nnseva** [comment]
Hi @charanjit-singh !

https://github.com/nnseva/django-jsoneditor#stable-version-from-the-pypi-repository

> Note that you should use one of original JSONField packages to provide the JSONField itself.

The json_field import in the optional file refers to one of the original JSONField packages providing JSONField **field** itself.
This package provides the only JSONEditor input **widget**.
