### ISSUE TITLE
JSON data is not being saved to the model

### ISSUE THREAD

**Issue by stuart-bradley** [nnseva/django-jsoneditor#49]
I'm having trouble saving the json created in the editor to my database. Everytime I run `save()` the `products` field is `None`.  I provided my `admin.py` and `models.py` below, is there anything I'm doing wrong? 

I imagine there might be an issue with using `django-nested-admin`, or possibly my Django version (3.0.2), but I'd like to rule out any dumb mistakes first
```
from jsoneditor.fields.postgres_jsonfield import JSONField
from django.db import models

class JsonModel(models.Model):
     products = JSONField(default=dict)
```

```
import nested_admin
from jsoneditor.fields.postgres_jsonfield import JSONField

class JsonModelInline(nested_admin.NestedTabularInline):
    model = models.JsonModel
    formfield_overrides = {
        JSONField: {'widget': JSONEditor},
    }
```

**Comment by nnseva** [comment]
Please, try to investigate an issue - exclude nested_admin, revert back to the Django 2.x - to ensure, what is the particular reason for the issue.

**Comment by moas** [comment]
Hi 
I've the same problem. When I edit jsonfield which use jsoneditor widget,  thé content not saved. So  cleaned_data return empty dictionnay

**Comment by nnseva** [comment]
@moas please report here your environment:
- Django version
- python version
- settings regarding to JSONEditor
- code snippet using JSONEditor

**Comment by moas** [comment]
django version 2.2.10
python: 3.6

INSTALLED_APPS = [...,"jsoneditor",...]

#json-editor
JSON_EDITOR_JS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/4.2.1/jsoneditor.js'
JSON_EDITOR_CSS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/4.2.1/jsoneditor.css'

#version
django-jsoneditor==0.1.4

```python

#models.py
from django.db import models
from django.contrib.postgres.fields import DateRangeField, JSONField
from django.utils.translation import ugettext_lazy as _
from model_utils.models import TimeStampedModel

class Foo(TimeStampedModel):
    metadata = JSONField(default=dict)

#admin.py
@admin.register(Foo)
class FooAdmin(admin.ModelAdmin):
    model = Foo
    form = FooForm
    formfield_overrides = {
        JSONField: {'widget': JSONEditor},
    }

#forms.py
class FooForm(forms.ModelForm):
    class Meta:
        model = Foo
        exclude = ("created", "modified")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["metadata"].required = False
```

**Comment by paced** [comment]
@moas, @lutrasdebtra Is this only happening on certain inputs or is it consistent for all JSON inputs?

**Comment by moas** [comment]
it works fine if I remove formfield_overrides (FooAdmin).

**Comment by paced** [comment]
@moas Well, that would remove the JSON editor in favour of the default editor, no?

It's alright, I'm just curious. I had a PR open that might have fixed this.

**Comment by nnseva** [comment]
@moas please remove lines
```
JSON_EDITOR_JS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/4.2.1/jsoneditor.js'
JSON_EDITOR_CSS = 'https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/4.2.1/jsoneditor.css'
```
from your settings file, or replace them by a reference to a more modern (5.x.x) JSONEditor version. I've found that the 4.2.1 version works wrong exactly as you've described.

Also, you should upgrade the `django-jsoneditor` package version to the last one.

The JSONEditor JavaScript code version provided with the `django-jsoneditor` package works fine.

**Comment by moas** [comment]
hi!

thx it fixed but css design is broken! so when I delete `form-row {
    overflow: visible;
}` design fixed!

**Comment by nnseva** [comment]
@moas `form-row { overflow: visible; }` has been overridden to allow tree actions menu overflow the form row div. It is actual in last Django versions 2.x and probably 3.x for too small trees.

Compare:

-----
(with fix)
![image](https://user-images.githubusercontent.com/496812/76444965-c1461180-63d5-11ea-9ac7-a8b35938af45.png)

-----

(without fix)
![image](https://user-images.githubusercontent.com/496812/76445192-141fc900-63d6-11ea-9c8f-49143fa59358.png)

**Comment by moas** [comment]
So with `form-row { overflow: visible; }`  my form design is broken, see below:
![css_broken_jsoneditor](https://user-images.githubusercontent.com/594529/76571339-90d6a400-64b7-11ea-8d2d-c56b22cc10a5.png)

**Comment by nnseva** [comment]
@moas can't reproduce. Did you try to clean browser caches?
