### ISSUE TITLE
Overflow style collapses the rows in django admin

### ISSUE THREAD

**Issue by inthedark122** [nnseva/django-jsoneditor#56]
Hello
I want to add extra json field with two exists fields
After adding all necessary packages my UI looks like on the screenshort

![image](https://user-images.githubusercontent.com/4956015/113407625-57205600-93b6-11eb-9e72-9d0c20afffce.png)

After removing in [file](https://github.com/nnseva/django-jsoneditor/blob/master/jsoneditor/static/django-jsoneditor/django-jsoneditor.css)

```
.form-row {
    overflow: visible;
}
```

my UI looks like as expected

Could you add more details why do you add this styles?

Thank you for this repository

**Comment by nnseva** [comment]
Hi! Previously, the context menu was hidden by the row border without this style in some Django versions. It was a workaround. I should check, whether the workaround is still necessary.

If you add a `help_text` attribute to your fields, the form will appear as expected.
