### ISSUE TITLE
New pypi version

### ISSUE THREAD

**Issue by mehdipourfar** [nnseva/django-jsoneditor#63]
Hi. Could you please sync pypi with project's tip?

**Comment by nnseva** [comment]
Did you mean the release version? Version 0.2.2 has just been issued.

Notice anyway that you could use prerelease versions explicitly for the pip or requirements.txt, like:

```shell
pip install "django-jsoneditor==0.2.1b1"
```

**Comment by mehdipourfar** [comment]
Thanks a lot.
